// SPDX-FileCopyrightText: © 2021 Uri Shaked <uri@wokwi.com>
// SPDX-License-Identifier: MIT

/* DO NOT EDIT - this is an auto-generated file. */
/* generated by gen_highorder_grid.py */

module silife_grid_16x16 (
    input wire reset,
    input wire clk,
    input wire enable,

    /* grid interconnect */
    input wire [15:0] i_n,
    input wire [15:0] i_e,
    input wire [15:0] i_s,
    input wire [15:0] i_w,
    input wire i_ne,
    input wire i_se,
    input wire i_sw,
    input wire i_nw,
    output wire [15:0] o_n,
    output wire [15:0] o_w,
    output wire [15:0] o_s,
    output wire [15:0] o_e,

    /* First port: read/write */
    input  wire [ 3:0] row_select,
    input  wire [15:0] clear_cells,
    input  wire [15:0] set_cells,
    output wire [15:0] cells,

    /* Second port: read only */
    input  wire [ 3:0] row_select2,
    output wire [15:0] cells2
);

  wire selected_y = row_select[3];
  assign cells = selected_y ? {cells_1_1, cells_1_0} : {cells_0_1, cells_0_0};
  assign cells2 = row_select2[3] ? {cells2_1_1, cells2_1_0} : {cells2_0_1, cells2_0_0};

  assign o_n = {n_0_1, n_0_0};
  assign o_e = {e_1_1, e_0_1};
  assign o_s = {s_1_1, s_1_0};
  assign o_w = {w_1_0, w_0_0};

  wire [255:0] cell_values = {
    subgrid_1_1.cell_values[63:56],
    subgrid_1_0.cell_values[63:56],
    subgrid_1_1.cell_values[55:48],
    subgrid_1_0.cell_values[55:48],
    subgrid_1_1.cell_values[47:40],
    subgrid_1_0.cell_values[47:40],
    subgrid_1_1.cell_values[39:32],
    subgrid_1_0.cell_values[39:32],
    subgrid_1_1.cell_values[31:24],
    subgrid_1_0.cell_values[31:24],
    subgrid_1_1.cell_values[23:16],
    subgrid_1_0.cell_values[23:16],
    subgrid_1_1.cell_values[15:8],
    subgrid_1_0.cell_values[15:8],
    subgrid_1_1.cell_values[7:0],
    subgrid_1_0.cell_values[7:0],
    subgrid_0_1.cell_values[63:56],
    subgrid_0_0.cell_values[63:56],
    subgrid_0_1.cell_values[55:48],
    subgrid_0_0.cell_values[55:48],
    subgrid_0_1.cell_values[47:40],
    subgrid_0_0.cell_values[47:40],
    subgrid_0_1.cell_values[39:32],
    subgrid_0_0.cell_values[39:32],
    subgrid_0_1.cell_values[31:24],
    subgrid_0_0.cell_values[31:24],
    subgrid_0_1.cell_values[23:16],
    subgrid_0_0.cell_values[23:16],
    subgrid_0_1.cell_values[15:8],
    subgrid_0_0.cell_values[15:8],
    subgrid_0_1.cell_values[7:0],
    subgrid_0_0.cell_values[7:0]
  };

  wire [7:0] n_0_0;
  wire [7:0] e_0_0;
  wire [7:0] s_0_0;
  wire [7:0] w_0_0;
  wire [7:0] cells_0_0;
  wire [7:0] cells2_0_0;

  silife_grid_8x8 subgrid_0_0 (
      .reset (reset),
      .clk   (clk),
      .enable(enable),

      .i_nw(i_nw),
      .i_n (i_n[7:0]),
      .i_ne(i_n[8]),
      .i_e (w_0_1),
      .i_se(n_1_1[0]),
      .i_s (n_1_0),
      .i_sw(i_w[8]),
      .i_w (i_w[7:0]),

      .o_n(n_0_0),
      .o_e(e_0_0),
      .o_s(s_0_0),
      .o_w(w_0_0),

      .row_select(row_select[2:0]),
      .clear_cells(selected_y == 1'b0 ? clear_cells[7:0] : 8'b0),
      .set_cells(selected_y == 1'b0 ? set_cells[7:0] : 8'b0),
      .cells(cells_0_0),

      .row_select2(row_select2[2:0]),
      .cells2(cells2_0_0)
  );


  wire [7:0] n_0_1;
  wire [7:0] e_0_1;
  wire [7:0] s_0_1;
  wire [7:0] w_0_1;
  wire [7:0] cells_0_1;
  wire [7:0] cells2_0_1;

  silife_grid_8x8 subgrid_0_1 (
      .reset (reset),
      .clk   (clk),
      .enable(enable),

      .i_nw(i_n[7]),
      .i_n (i_n[15:8]),
      .i_ne(i_ne),
      .i_e (i_e[7:0]),
      .i_se(i_e[8]),
      .i_s (n_1_1),
      .i_sw(n_1_0[7]),
      .i_w (e_0_0),

      .o_n(n_0_1),
      .o_e(e_0_1),
      .o_s(s_0_1),
      .o_w(w_0_1),

      .row_select(row_select[2:0]),
      .clear_cells(selected_y == 1'b0 ? clear_cells[15:8] : 8'b0),
      .set_cells(selected_y == 1'b0 ? set_cells[15:8] : 8'b0),
      .cells(cells_0_1),

      .row_select2(row_select2[2:0]),
      .cells2(cells2_0_1)
  );


  wire [7:0] n_1_0;
  wire [7:0] e_1_0;
  wire [7:0] s_1_0;
  wire [7:0] w_1_0;
  wire [7:0] cells_1_0;
  wire [7:0] cells2_1_0;

  silife_grid_8x8 subgrid_1_0 (
      .reset (reset),
      .clk   (clk),
      .enable(enable),

      .i_nw(i_w[7]),
      .i_n (s_0_0),
      .i_ne(s_0_1[0]),
      .i_e (w_1_1),
      .i_se(i_s[8]),
      .i_s (i_s[7:0]),
      .i_sw(i_sw),
      .i_w (i_w[15:8]),

      .o_n(n_1_0),
      .o_e(e_1_0),
      .o_s(s_1_0),
      .o_w(w_1_0),

      .row_select(row_select[2:0]),
      .clear_cells(selected_y == 1'b1 ? clear_cells[7:0] : 8'b0),
      .set_cells(selected_y == 1'b1 ? set_cells[7:0] : 8'b0),
      .cells(cells_1_0),

      .row_select2(row_select2[2:0]),
      .cells2(cells2_1_0)
  );


  wire [7:0] n_1_1;
  wire [7:0] e_1_1;
  wire [7:0] s_1_1;
  wire [7:0] w_1_1;
  wire [7:0] cells_1_1;
  wire [7:0] cells2_1_1;

  silife_grid_8x8 subgrid_1_1 (
      .reset (reset),
      .clk   (clk),
      .enable(enable),

      .i_nw(s_0_0[7]),
      .i_n (s_0_1),
      .i_ne(i_e[7]),
      .i_e (i_e[15:8]),
      .i_se(i_se),
      .i_s (i_s[15:8]),
      .i_sw(i_s[7]),
      .i_w (e_1_0),

      .o_n(n_1_1),
      .o_e(e_1_1),
      .o_s(s_1_1),
      .o_w(w_1_1),

      .row_select(row_select[2:0]),
      .clear_cells(selected_y == 1'b1 ? clear_cells[15:8] : 8'b0),
      .set_cells(selected_y == 1'b1 ? set_cells[15:8] : 8'b0),
      .cells(cells_1_1),

      .row_select2(row_select2[2:0]),
      .cells2(cells2_1_1)
  );



endmodule
